// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp33Txf1MfiOFy5bsO9vze3gYRhao3hKQ',
    appId: '1:926526274391:web:24baf159c8ff7482239c12',
    messagingSenderId: '926526274391',
    projectId: 'learn-6442d',
    authDomain: 'learn-6442d.firebaseapp.com',
    storageBucket: 'learn-6442d.appspot.com',
    measurementId: 'G-K9STS7QY40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQp-OoPU7-QmxwWxhbNJToXQGVOsgC6z0',
    appId: '1:926526274391:android:6dd848afc75889e1239c12',
    messagingSenderId: '926526274391',
    projectId: 'learn-6442d',
    storageBucket: 'learn-6442d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBei_DJ_Zh2KdIswSwAdUB1Vs0kWbHbc18',
    appId: '1:926526274391:ios:6feb880635912e5a239c12',
    messagingSenderId: '926526274391',
    projectId: 'learn-6442d',
    storageBucket: 'learn-6442d.appspot.com',
    iosClientId: '926526274391-v9lumba0di17f44i4ips85io4oo3431u.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBei_DJ_Zh2KdIswSwAdUB1Vs0kWbHbc18',
    appId: '1:926526274391:ios:6feb880635912e5a239c12',
    messagingSenderId: '926526274391',
    projectId: 'learn-6442d',
    storageBucket: 'learn-6442d.appspot.com',
    iosClientId: '926526274391-v9lumba0di17f44i4ips85io4oo3431u.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );
}
